source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.4.4'

gem 'aws-sdk'
gem 'aws-sdk-s3'
gem 'parallel'
gem 'mixlib-shellout'
gem 'redis'
gem 'rufus-scheduler'
gem 'httparty'
gem 'faraday'

